#!/bin/bash

DOTFILES_ROOT="${HOME}/.dotfiles"
DOTFILES_REPO="https://github.com/zgallup/dotfiles.git"

if [[ ! -d ${DOTFILES_ROOT} ]]; then
  git clone ${DOTFILES_REPO} ${DOTFILES_ROOT}
fi

cd ${DOTFILES_ROOT}

# vim
sudo apt-get install vim -y

# zsh
sudo apt-get install zsh
curl -L http://install.ohmyz.sh | sh

# install vundle 
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# symlink files
ln -sf ${DOTFILES_ROOT}/home/.aliases      ~/.aliases
ln -sf ${DOTFILES_ROOT}/home/.vimrc        ~/.vimrc
ln -sf ${DOTFILES_ROOT}/home/.vimrc.local  ~/.vimrc.local
ln -sf ${DOTFILES_ROOT}/home/.zshrc        ~/.zshrc

# import color scheme
git clone https://github.com/joshdick/onedark.vim.git

# create scheme directories
mkdir ~/.vim/colors
mkdir ~/.vim/autoload

# move scheme files
mv ${DOTFILES_ROOT}/onedark.vim/colors/onedark.vim  ~/.vim/colors/
mv ${DOTFILES_ROOT}/onedark.vim/autoload/onedark.vim  ~/.vim/autoload/

# vim plugins
vim +PluginInstall +qa
